apiVersion: v1
kind: Service
metadata:
    name: node-service-python
spec:
    type: NodePort
    selector:
        backend: python
    ports:
        - targetPort: 5000
          port: 5000
          nodePort: 30500
